### ISSUE TITLE
Update the document for betterunderstanding

### ISSUE THREAD

**Issue by kunalgupta1593** [quantumgraph/documentation#1]
Hi there , the document is very confusing as there is no proper switch for objective C and Swift. I had implemented your previous SDK on Friday but now i am trying to implement the new one today but the document is very very confusing as steps are mixed up in between.
Please modify your document for proper understanding and make some button on top for Objective-C and swift so that it is better understandable. Thanks

**Comment by quantumgraph** [comment]
Hi Kunal,
   Thanks for your feedback. Yes, I agree: the demarcation between objective C
and Swift is not clear. We'll improve it promptly.

**Comment by kunalgupta1593** [comment]
Thanks a lot for such a quick response. Looking forward for a new update ASAP 👍

**Comment by quantumgraph** [comment]
Hi Kunal, is your app built using Objective C or Swift?

**Comment by kunalgupta1593** [comment]
Hi
It is in swift

**Comment by quantumgraph** [comment]
We had separated ObjectiveC/Swift sections of documentation in September itself.
